# Generated by Django 4.1.3 on 2023-07-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_order_items_item_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("mm to sg", "MM to SG"), ("sg to mm", "SG to MM")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("mm to sg", "MM to SG"), ("sg to mm", "SG to MM")],
                        max_length=20,
                    ),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("air cargo", "Air Cargo"),
                            ("sea cargo", "Sea Cargo"),
                            ("land express", "Land Express"),
                            ("land cargo", "Land Cargo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("foods", models.DecimalField(decimal_places=2, max_digits=10)),
                ("clothes", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shoes_and_bags",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cosmetics", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medicines", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplements", models.DecimalField(decimal_places=2, max_digits=10)),
                ("electronics", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valuable_items",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[("mm to sg", "MM to SG"), ("sg to mm", "SG to MM")],
                default="none",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AddonChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.addon"
                    ),
                ),
            ],
        ),
    ]
