# Generated by Django 4.1.3 on 2023-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_addon_rule_remove_item_quantity_order_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="who_pay",
            field=models.CharField(
                choices=[("mm pay", "MM Pay"), ("sg pay", "SG Pay")],
                default="mm pay",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                ],
                max_length=20,
            ),
        ),
    ]
