# Generated by Django 4.1.3 on 2023-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_order_qr_code_alter_addonchoice_addon"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipientinfo",
            name="postal_code",
            field=models.CharField(default="123456", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="senderinfo",
            name="postal_code",
            field=models.CharField(default="123456", max_length=20),
            preserve_default=False,
        ),
    ]
