# Generated by Django 4.1.3 on 2023-08-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_recipientinfo_postal_code_senderinfo_postal_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_addons",
                        to="core.addon",
                    ),
                ),
                (
                    "addon_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_addons",
                        to="core.addonchoice",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_addons",
                        to="core.order",
                    ),
                ),
            ],
        ),
    ]
