# Generated by Django 4.1.3 on 2023-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_orderaddon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True, default="Outdated-ID", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shelf_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
